workflows:
  react-native-workflow:
    name: React Native Workflow
    max_build_duration: 120
    environment:
      vars:
        NODE_VERSION: 14.17.0
        EXPO_CLI_VERSION: latest
        EAS_CLI_VERSION: latest
        EXPO_USERNAME: shakeeb2024
        EXPO_PASSWORD: 2262Sha@
      node: $NODE_VERSION
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Set up React Native environment
        script: |
          npm install -g expo-cli@$EXPO_CLI_VERSION
          npm install -g eas-cli@$EAS_CLI_VERSION
          expo login --username $EXPO_USERNAME --password $EXPO_PASSWORD
      - name: Build Android APK
        script: |
          eas build -p android --non-interactive || { echo "EAS build failed"; exit 1; }
          if [ -f "$(ls $CM_BUILD_DIR/build/*.apk 2>/dev/null)" ]; then
            mkdir -p $CM_BUILD_DIR/build_outputs/apk
            mv $CM_BUILD_DIR/build/*.apk $CM_BUILD_DIR/build_outputs/apk/
          else
            echo "APK not found, build might have failed"
            exit 1
          fi
      - name: Build iOS IPA
        script: |
          eas build -p ios --non-interactive || { echo "EAS build failed"; exit 1; }
          if [ -f "$(ls $CM_BUILD_DIR/build/*.ipa 2>/dev/null)" ]; then
            mkdir -p $CM_BUILD_DIR/build_outputs/ipa
            mv $CM_BUILD_DIR/build/*.ipa $CM_BUILD_DIR/build_outputs/ipa/
          else
            echo "IPA not found, build might have failed"
            exit 1
          fi
    artifacts:
      - build_outputs/**/*
    publishing:
      email:
        recipients:
          - shakeebjasim.mail@gmail.com
